change-detector:
  invoke:
    cron: 0 */10 * ? * *
  loader:
    pull-from-db: false # true should be set only first time
  detect:
    since-last: 3
    time-unit: DAYS
    max-process-await: 5
    max-process-await-time-unit: MINUTES
  store:
    expire:
      in: 72
      time-unit: HOURS

quarkus:
  application:
    name: airq-change-detector
  datasource:
    db-kind: postgresql
    username: postgres
    jdbc:
      url: jdbc:postgresql://10.1.1.50:5432/warehouse
    reactive:
      url: postgresql://10.1.1.50:5432/warehouse
  vertx:
    prefer-native-transport: true

mp:
  messaging:
    outgoing:
      gios-installation:
        connector: smallrye-kafka
        topic: gios.installation
        key:
          serializer: pl.airq.common.kafka.TSKeySerializer
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  group:
    id: airq-change-detector
  bootstrap:
    servers: 10.1.1.51:9092

"%dev":
  change-detector:
    pull:
      cron: 0 */2 * ? * *
    loader:
      pull-from-db: true
    store:
      expire:
        in: 72
        timeUnit: HOURS

  quarkus:
    redis:
      hosts: redis://localhost:6379

  kafka:
    bootstrap:
      servers: localhost:9092

"%test":
  quarkus:
    scheduler:
      enabled: false

  change-detector:
    store:
      expire:
        in: 5
        timeUnit: SECONDS
