change-detector:
  invoke:
    cron: 0 */10 * ? * *
  loader:
    pullFromDb: false
  detect:
    sinceLast: 3
    timeUnit: DAYS
    maxProcessAwait: 5
    maxProcessAwaitTimeUnit: MINUTES
  store:
    expire:
      in: 72
      timeUnit: HOURS

quarkus:
  application:
    name: airq-change-detector
  datasource:
    db-kind: postgresql
    username: postgres
    jdbc:
      url: jdbc:postgresql://10.1.1.50:5432/warehouse
    reactive:
      url: postgresql://10.1.1.50:5432/warehouse
  redis:
    password:
  vertx:
    prefer-native-transport: true

mp:
  messaging:
    outgoing:
      gios-installation:
        connector: smallrye-kafka
        topic: gios.installation
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  group:
    id: airq-change-detector
  bootstrap:
    servers: 10.1.1.51:9092

"%dev":
  change-detector:
    pull:
      cron: 0 0 * * * ?
    store:
      expire:
        in: 72
        timeUnit: HOURS

  quarkus:
    redis:
      hosts: localhost:6379

  kafka:
    bootstrap:
      servers: localhost:9092
